### ISSUE TITLE
Impossible to stop session after press "Start" button twice or more 

### ISSUE THREAD

**Issue by welxeorwel** [psynext/emdr-site#7]
Impossible to stop session after press "Start" button twice more. Menu becomes available and possible to change settings, but balls don`t stop. 
Steps 
1) Open  emdr site.
2) Press "Start" button. twice 
3) Press "Stop" button.

Expected res 
Menu available, balls at start position, and possible to start new session.   
Actual res 
Menu available but balls moves and isn't possible to start new session until the time is out.

**Comment by skad0** [comment]
fixed by disabling button
